version: '3.8'

services:
  
  app:
    container_name: grant_app
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/test

  mongo:
    container_name: grant_mongo
    image: mongo:6-jammy
    ports:
      - '27017:27017'
